# Site settings
name: Park Jin Soo
title: Park Jin Soo | Backend Engineer
description:
url: https://j00r6.github.io/
baseurl: ''
email: mailto:jindory8@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:jindory8@gmail.com
  - title: github
    url: https://github.com/j00r6

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
